name: Record Cross Browser End-to-End Testing to cypress cloud

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run docker-compose with Cypress Cloud recording
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        run: docker-compose up -d e2e-chrome e2e-firefox e2e-edge e2e-electron

      - name: Wait for tests to complete
        run: sleep 60 && docker-compose logs -f

      - name: Upload Chrome artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chrome-artifacts
          path: |
            ./artifacts/chrome/videos
            ./artifacts/chrome/screenshots
          if-no-files-found: ignore
          retention-days: 5

      - name: Upload Firefox artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firefox-artifacts
          path: ./artifacts/firefox/screenshots
          if-no-files-found: ignore
          retention-days: 5

      - name: Upload Edge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: edge-artifacts
          path: |
            ./artifacts/edge/videos
            ./artifacts/edge/screenshots
          if-no-files-found: ignore
          retention-days: 5

      - name: Upload Electron artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-artifacts
          path: |
            ./artifacts/electron/videos
            ./artifacts/electron/screenshots
          if-no-files-found: ignore
          retention-days: 5
