name: Record Cross Browser End-to-End Testing to Cypress Cloud

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        browser: [chrome, firefox, edge, electron] # Define matrix to run each browser separately

    steps:
      - name: Checkout Repository 🛎
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Cypress in Parallel on ${{ matrix.browser }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CI_BUILD_ID: ${{ github.run_id }}
        run: |
          docker-compose up -d e2e-${{ matrix.browser }}
          sleep 60
          docker-compose logs -f
          docker-compose down

      - name: Upload Test Artifacts for ${{ matrix.browser }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.browser }}-artifacts
          path: |
            ./artifacts/${{ matrix.browser }}/videos
            ./artifacts/${{ matrix.browser }}/screenshots
          if-no-files-found: ignore
          retention-days: 5
