name: Cypress Tests

on:
  push:
    branches:
      - main # Or any branch you'd like to trigger the tests on

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge] # List of browsers for parallelization

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # Checkout code from the repo

      - name: Install Dependencies
        run: npm ci # Use npm ci to install dependencies from package-lock.json

      - name: Cypress Run on ${{ matrix.browser }}
        uses: cypress-io/github-action@v6 # Use latest Cypress GitHub Action
        with:
          start: npm start
          browser: ${{ matrix.browser }} # Run tests on the specified browser
          record: true # Record tests on Cypress Dashboard
          parallel: true # Run tests in parallel across containers
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} # Required for recording tests
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for API access
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }} # Your Cypress project ID
