name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge] # List of browsers
        containers: [1, 2] # Uses 2 parallel instances per browser

    steps:
      - name: Install Microsoft Edge
        run: |
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
          sudo apt update
          sudo apt install microsoft-edge-stable

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cypress run on ${{ matrix.browser }}
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: ${{ matrix.browser }} # Run on the specified browser
          record: true
          parallel: true # Runs tests in parallel across instances
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
